/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Балл по шкале 1–10.
 */
export type Score = number;

/**
 * Одна запись grounding-корпуса: ответы реального респондента фокус-группы. Схема написана ПО ФАКТИЧЕСКИМ ДАННЫМ 165 записей data/grounding/unified_respondent_sessions.json, а не по представлениям о них. Перечисления закрыты только там, где домен действительно закрыт: пол, возрастная группа, тип населённого пункта и четыре шкалы восприятия. Города, эмоции, ценности и тип контента оставлены открытыми строками — они пополняются с каждым новым исследованием, и закрытое перечисление там ломало бы корпус при добавлении данных, а не защищало его.
 */
export interface RespondentSession {
  /**
   * Идентификатор вида «<Исследование>_<номер>». Производный от источника и порядкового номера, не от имени человека — обезличивание.
   */
  respondent_id: string;
  /**
   * Имя исходного файла анкет ЦЕЛИКОМ, с расширением. Ключ связи записи с исследованием.
   */
  source_file: string;
  content_under_test: {
    title: string;
    /**
     * Открытая строка: в корпусе пока только «сериал», но полнометражные и рекламные ролики предполагаются.
     */
    type: string;
    summary: string;
  };
  experiment_metadata: {
    focus_group_city: string;
    /**
     * Сегмент, под который набиралась группа. Открытая строка: сегменты задаёт заказчик исследования.
     */
    target_audience_segment: string;
    transcript_source_file: string;
  };
  socio_demographics: {
    gender: "жен" | "муж";
    age: number;
    /**
     * Словарь совпадает с persona-dna.schema.json. Расхождение делает метрику persona_grounding невычислимой.
     */
    age_group: "14-17" | "18-24" | "25-34" | "35-44" | "45-59" | "60+";
    /**
     * Тип населённого пункта в терминах выборки исследования.
     */
    geo: "столицы" | "центры субъектов";
    city: string;
    children: string;
  };
  psychographics_and_values: {
    /**
     * Ценности, которые респондент считает важными. Открытый список: в корпусе 27 различных формулировок.
     */
    important_values: string[];
  };
  /**
   * Пять базовых критериев AGORA. Именно по ним считается калибровка |средние−реальные| ≤ 1.0.
   */
  agora_core_scores_1_to_10: {
    overall_impression: Score;
    plot: Score;
    acting: Score;
    music: Score;
    cinematography: Score;
  };
  perception_and_retention: {
    interest_level: "Скорее интересен" | "Скорее не интересен" | "Затрудняюсь ответить";
    /**
     * Открытый список. ВНИМАНИЕ: в текущем корпусе сюда затесались подписи шкалы («10 – вызвал очень сильные эмоции») и голые числа — известный дефект данных, см. data/grounding/corpus.meta.json.
     */
    emotions_evoked: string[];
    idea_comprehension: "Скорее понятно" | "Скорее не понятно" | "Затрудняюсь ответить";
    realism_perception: "Скорее реалистичные" | "Скорее нереалистичные" | "Затрудняюсь ответить";
    retention_intent:
      "Скорее хотелось досмотреть до конца" | "Скорее хотелось остановить просмотр" | "Затрудняюсь ответить";
    recommendation_nps_1_to_10: Score;
  };
  /**
   * Открытые ответы из анкеты. why_impression заполнен не у всех: 156 записей из 165.
   */
  qualitative_verbatims: {
    idea_comprehension_comment: string;
    general_impression_comment: string;
    why_impression?: string;
  };
  /**
   * Срез групповой дискуссии под конкретного респондента: реплики с указанием говорящего. Получен моделью по промпту dataset.unification при первичной сборке корпуса и НЕ воспроизводится механически — см. corpus.meta.json.
   */
  focus_group_verbatims: string[];
  /**
   * Сырая анкета как есть: ключи — формулировки вопросов из XLSX, поэтому набор ключей различается между исследованиями. Намеренно ненормализованный слепок источника, нужен для прослеживаемости: по нему можно проверить любое нормализованное поле выше. Схема тут не ограничивает ключи — ограничение сделало бы добавление нового исследования невозможным.
   */
  all_survey_responses: {
    [k: string]: string | number | boolean | null;
  };
}
