/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Question = {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  [k: string]: unknown;
} & {
  /**
   * Идентификатор вопроса. У базовых — base-1..base-5, у пользовательских — uuid или custom-N.
   */
  id: string;
  /**
   * Задан только у пяти базовых критериев; у пользовательских — отсутствует.
   */
  baseKey?: BaseCriterionKey | null;
  /**
   * Формулировка вопроса. Подпись менять можно, baseKey — нет.
   */
  label: string;
  type: QuestionType;
  /**
   * Нижняя граница шкалы. Осмысленна и обязательна только при type=scale; у выбора из списка шкалы нет, и требовать её значило бы заставлять конструктор писать числа, которых у вопроса нет.
   */
  scaleMin?: number;
  /**
   * Верхняя граница шкалы. При type=scale должна быть больше scaleMin.
   */
  scaleMax?: number;
  /**
   * Подсказка для персоны — что именно оценивать. Необязательна.
   */
  hint?: string;
  /**
   * Блок верхнего уровня. Даёт двухуровневую шапку выгрузки — «блок / вопрос», — в форме которой заказчик получает свои полевые файлы, и смысловые разделы отчёта.
   */
  block?: string;
  /**
   * Номер вопроса в анкете заказчика. Нужен, чтобы отчёт и выгрузка называли вопрос так же, как его называет заказчик.
   */
  number?: number;
  /**
   * Варианты ответа. Закрытый вопрос БЕЗ вариантов — это открытый вопрос: персона ответит своими словами, и доли не сойдутся с закрытым списком.
   *
   * @maxItems 100
   */
  options?: Option[];
  /**
   * Потолок выбора при type=multi_choice. Без него модель выберет столько, сколько захочет, и доли перестанут быть сравнимыми с полевыми волнами.
   */
  maxChoices?: number;
  /**
   * Варианты, выбираемые только в одиночку: «не испытал никаких эмоций», «затрудняюсь ответить».
   *
   * @maxItems 20
   */
  exclusiveOptionIds?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  /**
   * Строки матрицы при type=matrix_single.
   *
   * @maxItems 200
   */
  rows?: MatrixRow[];
  /**
   * Темы матрицы. Оператор выбирает темами, а не строками.
   *
   * @maxItems 50
   */
  themes?: Theme[];
  /**
   * Вопрос, выбор тем в котором определяет состав строк этого вопроса. Так вопрос 11 заказчика добавляется по темам вопроса 9.
   */
  dependsOnQuestion?: string;
  /**
   * Единица выбора оператора. «theme» — тема включается целиком со всеми строками; иначе интегральный показатель восприятия считался бы по разному числу строк и стал бы несравним между прогонами.
   */
  selectableBy?: "theme";
  reporting?: Reporting;
  /**
   * Идентификаторы вариантов, которые оператор отметил ключевыми для отдельного расчета.
   */
  keyOptionIds?: string[];
  /**
   * Пометка для разработчика. Персоне не показывается.
   */
  note?: string;
} & {
  /**
   * Идентификатор вопроса. У базовых — base-1..base-5, у пользовательских — uuid или custom-N.
   */
  id: string;
  /**
   * Задан только у пяти базовых критериев; у пользовательских — отсутствует.
   */
  baseKey?: BaseCriterionKey | null;
  /**
   * Формулировка вопроса. Подпись менять можно, baseKey — нет.
   */
  label: string;
  type: QuestionType;
  /**
   * Нижняя граница шкалы. Осмысленна и обязательна только при type=scale; у выбора из списка шкалы нет, и требовать её значило бы заставлять конструктор писать числа, которых у вопроса нет.
   */
  scaleMin?: number;
  /**
   * Верхняя граница шкалы. При type=scale должна быть больше scaleMin.
   */
  scaleMax?: number;
  /**
   * Подсказка для персоны — что именно оценивать. Необязательна.
   */
  hint?: string;
  /**
   * Блок верхнего уровня. Даёт двухуровневую шапку выгрузки — «блок / вопрос», — в форме которой заказчик получает свои полевые файлы, и смысловые разделы отчёта.
   */
  block?: string;
  /**
   * Номер вопроса в анкете заказчика. Нужен, чтобы отчёт и выгрузка называли вопрос так же, как его называет заказчик.
   */
  number?: number;
  /**
   * Варианты ответа. Закрытый вопрос БЕЗ вариантов — это открытый вопрос: персона ответит своими словами, и доли не сойдутся с закрытым списком.
   *
   * @maxItems 100
   */
  options?: Option[];
  /**
   * Потолок выбора при type=multi_choice. Без него модель выберет столько, сколько захочет, и доли перестанут быть сравнимыми с полевыми волнами.
   */
  maxChoices?: number;
  /**
   * Варианты, выбираемые только в одиночку: «не испытал никаких эмоций», «затрудняюсь ответить».
   *
   * @maxItems 20
   */
  exclusiveOptionIds?:
    | []
    | [string]
    | [string, string]
    | [string, string, string]
    | [string, string, string, string]
    | [string, string, string, string, string]
    | [string, string, string, string, string, string]
    | [string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [string, string, string, string, string, string, string, string, string, string, string, string, string, string]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ]
    | [
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        string
      ];
  /**
   * Строки матрицы при type=matrix_single.
   *
   * @maxItems 200
   */
  rows?: MatrixRow[];
  /**
   * Темы матрицы. Оператор выбирает темами, а не строками.
   *
   * @maxItems 50
   */
  themes?: Theme[];
  /**
   * Вопрос, выбор тем в котором определяет состав строк этого вопроса. Так вопрос 11 заказчика добавляется по темам вопроса 9.
   */
  dependsOnQuestion?: string;
  /**
   * Единица выбора оператора. «theme» — тема включается целиком со всеми строками; иначе интегральный показатель восприятия считался бы по разному числу строк и стал бы несравним между прогонами.
   */
  selectableBy?: "theme";
  reporting?: Reporting;
  /**
   * Идентификаторы вариантов, которые оператор отметил ключевыми для отдельного расчета.
   */
  keyOptionIds?: string[];
  /**
   * Пометка для разработчика. Персоне не показывается.
   */
  note?: string;
};
/**
 * Ключи базовых критериев. Именно по ним посчитаны средние в корпусе 165 респондентов — ключ часть контракта с данными, не подпись. Присутствие каждого НЕобязательно; снятый критерий отключает сравнение с корпусом по нему, и об этом говорит конструктор. Присутствующий обязан быть шкалой 0–10: расчёты Приложения 2 читают баллы абсолютными порогами, и другая шкала дала бы правдоподобные, но неверные показатели.
 */
export type BaseCriterionKey = "overall_impression" | "plot" | "acting" | "music" | "cinematography";
/**
 * Типы вопроса. Список закрытый: воркер умеет разбирать ответ только этих форм, и добавление типа — изменение схемы ответа персоны, а не правка интерфейса.
 *
 * 17.09.2026 прежние шесть сведены к пяти. «Эмоции», «удержание», «рекомендация» и «доля просмотра» были не типами, а ПРЕСЕТАМИ: эмоции — выбор нескольких из готового словаря, удержание — выбор одного из трёх, рекомендация и доля — шкалы. Каждый нёс свою ветку в конструкторе, промпте, правилах QA, агрегате, графиках и выгрузке; свёрнутые, они дают один редьюсер и один график на тип. Пресет живёт в данных анкеты (готовый `options`), а не в перечне типов.
 */
export type QuestionType = "scale" | "single_choice" | "multi_choice" | "matrix_single" | "open";
export type ReportingChart = "scale" | "scale_top_box" | "bars" | "donut" | "matrix_stacked" | "nps";
export type ReportingGroup = "positive" | "negative" | "neutral" | "unknown";

/**
 * Анкета исследования. Контракт между конструктором анкеты (фронт) и воркером (бэк). Валидируется при INSERT в surveys.questions. Базовые критерии необязательны: владелец вправе снять любое их число и спрашивать своё.
 */
export interface Survey {
  /**
   * UUID анкеты. Генерируется базой при INSERT.
   */
  id?: string;
  /**
   * Название анкеты. Обязательно.
   */
  name: string;
  /**
   * Список вопросов. Базовые критерии, если они есть, идут первыми, за ними пользовательские. Минимум один вопрос: анкета без вопросов означает прогон, в котором персону не о чем спрашивать, а стоит он столько же.
   *
   * @minItems 1
   */
  questions: [Question, ...Question[]];
  /**
   * Время создания. Устанавливается базой.
   */
  created_at?: string;
}
/**
 * Вариант ответа закрытого вопроса. Ответ персоны адресует вариант ИДЕНТИФИКАТОРОМ: подпись правят, идентификатор — нет. На подписи держалось бы то самое расхождение «писатель и читатель разошлись по строке», которое в этом репозитории чинили четырежды.
 */
export interface Option {
  /**
   * Уникален внутри вопроса. Попадает в ответ персоны и в колонку выгрузки.
   */
  id: string;
  /**
   * Подпись варианта. Её видит персона и читатель отчёта.
   */
  label: string;
  /**
   * Служебный вариант вроде «Затрудняюсь ответить». В долях по содержательным вариантам не участвует, но остаётся в знаменателе: доли считаются «в % от опрошенных», как подписано у заказчика.
   */
  service?: boolean;
}
/**
 * Строка матрицы. Ответ даётся ПО КАЖДОЙ строке, поэтому строка — единица покрытия анкеты, а не вопрос: сорок три подтемы вопроса 9 это сорок три поля, а не одно.
 *
 * Свои `options` у строки означают, что список вариантов принадлежит ИМЕННО ей. Без них берутся общие у вопроса — так устроен вопрос 9 заказчика, где один список повторяется на всех подтемах. У своей матрицы оператора вопросы внутри темы разные («поднималась / не поднималась» и «финал / музыка / герой»), и общий список склеил бы их: персоне предложили бы варианты чужого вопроса, а её ответ разобрался бы против них же — без отказа и с правдоподобной долей на графике.
 */
export interface MatrixRow {
  id: string;
  label: string;
  /**
   * Тема, к которой относится строка. По ней оператор включает блок целиком и по ней же считается интегральный показатель.
   */
  themeId?: string;
  /**
   * Варианты ответа именно этой строки. Без них берутся общие у вопроса.
   *
   * @minItems 2
   * @maxItems 100
   */
  options?: [Option, Option, ...Option[]];
  /**
   * Сколько вариантов персона выбирает в этой строке. Без него — ровно один. Больше, чем вариантов у строки, задать нельзя: это обещание, которого анкета не выполнит, а в отчёте доли сойдутся по тем, что есть, и будут выглядеть так же уверенно.
   */
  maxChoices?: number;
}
/**
 * Тема матрицы. Единица выбора оператора: галочка ставится на теме, и все её строки идут в анкету целиком.
 */
export interface Theme {
  id: string;
  label: string;
}
/**
 * Метаданные диаграммы и классификация вариантов для отчета. Необязательно для старых анкет.
 */
export interface Reporting {
  chart: ReportingChart;
  center?: ReportingGroup;
  /**
   * Специальные показатели полярности эмоций, которые показываются только для этого вопроса.
   */
  polarity?: "emotions";
  groups?: {
    positive?: string[];
    negative?: string[];
    neutral?: string[];
    unknown?: string[];
  };
}
