/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Ключи пяти базовых критериев. Именно по ним посчитаны средние в корпусе 165 респондентов — ключ часть контракта с данными, не подпись.
 */
export type BaseCriterionKey = "overall_impression" | "plot" | "acting" | "music" | "cinematography";
/**
 * Типы вопросов P1-конструктора. Список закрытый: воркер умеет разбирать ответ только этих пяти форм. Добавление шестого — изменение схемы ответа персоны.
 */
export type QuestionType = "scale" | "emotions" | "retention" | "recommendation" | "open";

export interface Survey {
  /**
   * UUID анкеты. Генерируется базой при INSERT.
   */
  id?: string;
  /**
   * Название анкеты. Обязательно.
   */
  name: string;
  /**
   * Список вопросов. Первый блок — пять базовых критериев (P0), за ними — пользовательские (P1).
   * @minItems 5
   */
  questions: Question[];
  /**
   * Время создания. Устанавливается базой.
   */
  created_at?: string;
  [k: string]: unknown;
}

export interface Question {
  /**
   * Идентификатор вопроса. У базовых — base-1..base-5, у пользовательских — uuid или custom-N.
   */
  id: string;
  /**
   * Задан только у пяти базовых критериев; у пользовательских — отсутствует.
   */
  baseKey?: BaseCriterionKey | null;
  /**
   * Формулировка вопроса. Подпись менять можно, baseKey — нет.
   */
  label: string;
  type: QuestionType;
  /**
   * Нижняя граница шкалы. Осмысленна только при type=scale, но поле обязательное — упрощает валидацию.
   */
  scaleMin: number;
  /**
   * Верхняя граница шкалы. При type=scale должна быть больше scaleMin.
   */
  scaleMax: number;
  /**
   * Подсказка для персоны — что именно оценивать. Необязательна.
   */
  hint?: string;
  [k: string]: unknown;
}