# generated by datamodel-codegen:
#   filename:  persona-dna.schema.json
#   timestamp: 2026-08-01T17:52:04+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Gender(Enum):
    муж = 'муж'
    жен = 'жен'


class AgeGroup(Enum):
    field_14_17 = '14-17'
    field_18_24 = '18-24'
    field_25_34 = '25-34'
    field_35_44 = '35-44'
    field_45_59 = '45-59'
    field_60_ = '60+'


class Geo(Enum):
    столицы = 'столицы'
    центры_субъектов = 'центры субъектов'
    иные_НП = 'иные НП'


class Children(Enum):
    Да__есть_ребенок___дети = 'Да, есть ребенок / дети'
    Нет_детей = 'Нет детей'
    Не_указано = 'Не указано'


class Demographics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gender: Gender = Field(
        ...,
        description='Пол. Совпадает со значениями корпуса unified_respondent_sessions.json.',
    )
    age: conint(ge=14, le=80) = Field(..., description='Возраст в годах.')
    age_group: AgeGroup = Field(
        ...,
        description='Возрастная группа. Перечисление взято из фактических значений корпуса.',
    )
    geo: Geo = Field(
        ..., description='Тип населённого пункта. Перечисление из корпуса.'
    )
    city: str = Field(..., description='Название города.')
    children: Children = Field(..., description='Наличие детей.')


class BigFive(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    openness: conint(ge=1, le=5) = Field(..., description='Открытость опыту.')
    conscientiousness: conint(ge=1, le=5) = Field(..., description='Добросовестность.')
    extraversion: conint(ge=1, le=5) = Field(..., description='Экстраверсия.')
    agreeableness: conint(ge=1, le=5) = Field(..., description='Доброжелательность.')
    neuroticism: conint(ge=1, le=5) = Field(..., description='Нейротизм.')


class Worldview(Enum):
    традиционалистская = 'традиционалистская'
    либеральная = 'либеральная'
    консервативная = 'консервативная'
    прагматическая = 'прагматическая'
    неопределённая = 'неопределённая'


class PoliticalOrientation(Enum):
    аполитичен = 'аполитичен'
    умеренно_консервативный = 'умеренно-консервативный'
    умеренно_либеральный = 'умеренно-либеральный'
    активно_консервативный = 'активно-консервативный'
    активно_либеральный = 'активно-либеральный'


class ReligiousAttitude(Enum):
    воцерковлённый = 'воцерковлённый'
    верующий_невоцерковлённый = 'верующий невоцерковлённый'
    agnostic = 'agnostic'
    атеист = 'атеист'


class ValuesAndBeliefs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    important_values: list[str] = Field(..., min_length=1)
    worldview: Worldview = Field(..., description='Мировоззренческая ориентация.')
    political_orientation: PoliticalOrientation = Field(
        ..., description='Политическая ориентация.'
    )
    religious_attitude: ReligiousAttitude = Field(
        ..., description='Отношение к религии.'
    )


class PreferredGenre(Enum):
    драма = 'драма'
    комедия = 'комедия'
    триллер = 'триллер'
    детектив = 'детектив'
    мелодрама = 'мелодрама'
    фантастика = 'фантастика'
    фэнтези = 'фэнтези'
    исторический = 'исторический'
    документальный = 'документальный'
    реалити_шоу = 'реалити-шоу'
    анимация = 'анимация'
    хоррор = 'хоррор'
    боевик = 'боевик'
    криминал = 'криминал'
    военный = 'военный'
    спорт = 'спорт'


class ViolenceTolerance(Enum):
    низкая = 'низкая'
    средняя = 'средняя'
    высокая = 'высокая'


class PacingTolerance(Enum):
    медленный = 'медленный'
    умеренный = 'умеренный'
    быстрый = 'быстрый'


class LengthTolerance(Enum):
    короткие_ролики = 'короткие ролики'
    серии_20_40_мин = 'серии 20-40 мин'
    полноценные_серии_40_60_мин = 'полноценные серии 40-60 мин'
    полные_фильмы = 'полные фильмы'


class IdeologicalResponse(Enum):
    отвергает = 'отвергает'
    критичен = 'критичен'
    нейтрален = 'нейтрален'
    восприимчив = 'восприимчив'
    ищет = 'ищет'


class AdResponse(Enum):
    раздражение = 'раздражение'
    игнорирование = 'игнорирование'
    нейтральное = 'нейтральное'
    интерес = 'интерес'
    доверие = 'доверие'


class ProductionExpectations(Enum):
    низкие = 'низкие'
    средние = 'средние'
    высокие = 'высокие'


class AttentionSpan(Enum):
    короткий = 'короткий'
    средний = 'средний'
    длинный = 'длинный'


class ViewerBehavior(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    preferred_genres: list[PreferredGenre] = Field(..., min_length=1)
    violence_tolerance: ViolenceTolerance = Field(
        ..., description='Толерантность к насилию на экране.'
    )
    pacing_tolerance: PacingTolerance = Field(
        ..., description='Предпочитаемый темп повествования.'
    )
    length_tolerance: LengthTolerance = Field(
        ..., description='Толерантность к длине контента.'
    )
    franchise_loyalty: conint(ge=1, le=5) = Field(
        ...,
        description='Лояльность к франшизам (1 — не важна, 5 — определяет просмотр).',
    )
    actor_loyalty: conint(ge=1, le=5) = Field(
        ..., description='Лояльность к актёрам (1 — не важна, 5 — определяет просмотр).'
    )
    recommendation_influence: conint(ge=1, le=5) = Field(
        ..., description='Влияние рекомендаций (1 — не влияют, 5 — решающее).'
    )
    ideological_response: IdeologicalResponse = Field(
        ..., description='Реакция на идеологические посылы.'
    )
    ad_response: AdResponse = Field(..., description='Реакция на рекламные посылы.')
    production_expectations: ProductionExpectations = Field(
        ..., description='Ожидания от качества продакшена.'
    )
    attention_span: AttentionSpan = Field(
        ..., description='Способность удерживать внимание.'
    )


class Verbosity(Enum):
    лаконичный = 'лаконичный'
    умеренный = 'умеренный'
    подробный = 'подробный'


class Directness(Enum):
    прямой = 'прямой'
    окольный = 'окольный'
    завуалированный = 'завуалированный'


class Emotionality(Enum):
    сдержанный = 'сдержанный'
    умеренный = 'умеренный'
    эмоциональный = 'эмоциональный'


class Humor(Enum):
    без_юмора = 'без юмора'
    ироничный = 'ироничный'
    добродушный = 'добродушный'
    саркастический = 'саркастический'


class ConflictStyle(Enum):
    избегание = 'избегание'
    компромисс = 'компромисс'
    конфронтация = 'конфронтация'
    сотрудничество = 'сотрудничество'


class CommunicationStyle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    verbosity: Verbosity = Field(..., description='Многословность.')
    directness: Directness = Field(..., description='Прямота высказываний.')
    emotionality: Emotionality = Field(
        ..., description='Эмоциональная выразительность.'
    )
    humor: Humor = Field(..., description='Стиль юмора.')
    conflict_style: ConflictStyle = Field(
        ..., description='Стиль поведения в конфликте.'
    )


class Style(Enum):
    рациональный = 'рациональный'
    эмоциональный = 'эмоциональный'
    интуитивный = 'интуитивный'
    смешанный = 'смешанный'


class DecisionMaking(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    style: Style = Field(..., description='Стиль принятия решений.')
    risk_appetite: conint(ge=1, le=5) = Field(
        ..., description='Склонность к риску (1 — избегает, 5 — ищет).'
    )
    brand_loyalty: conint(ge=1, le=5) = Field(
        ...,
        description='Лояльность к брендам/платформам (1 — легко меняет, 5 — предан).',
    )
    impulsivity: conint(ge=1, le=5) = Field(
        ..., description='Импульсивность решений (1 — взвешенный, 5 — спонтанный).'
    )


class Device(Enum):
    smartphone = 'smartphone'
    tablet = 'tablet'
    laptop = 'laptop'
    smart_tv = 'smart-tv'
    desktop = 'desktop'


class Platform(Enum):
    YouTube = 'YouTube'
    Кинопоиск = 'Кинопоиск'
    Иви = 'Иви'
    Okko = 'Okko'
    Premier = 'Premier'
    Wink = 'Wink'
    VK_Видео = 'VK Видео'
    Telegram = 'Telegram'
    Яндекс_Дзен = 'Яндекс.Дзен'
    VK = 'VK'
    Одноклассники = 'Одноклассники'


class SocialMediaEnum(Enum):
    Telegram = 'Telegram'
    VK = 'VK'
    Одноклассники = 'Одноклассники'
    WhatsApp = 'WhatsApp'
    Viber = 'Viber'
    не_пользуется = 'не пользуется'


class StreamingFrequency(Enum):
    редко = 'редко'
    раз_в_неделю = 'раз в неделю'
    несколько_раз_в_неделю = 'несколько раз в неделю'
    ежедневно = 'ежедневно'


class TechnologyUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    devices: list[Device] = Field(..., min_length=1)
    platforms: list[Platform]
    social_media: list[SocialMediaEnum]
    streaming_frequency: StreamingFrequency = Field(
        ..., description='Частота просмотра стримингового контента.'
    )
    tech_savviness: conint(ge=1, le=5) = Field(
        ..., description='Техническая грамотность (1 — базовая, 5 — продвинутая).'
    )


class Hobby(Enum):
    чтение = 'чтение'
    кино_сериалы = 'кино/сериалы'
    спорт = 'спорт'
    путешествия = 'путешествия'
    готовка = 'готовка'
    музыка = 'музыка'
    игры = 'игры'
    рукоделие = 'рукоделие'
    садоводство = 'садоводство'
    рыбалка_охота = 'рыбалка/охота'
    коллекционирование = 'коллекционирование'
    волонтёрство = 'волонтёрство'
    танцы = 'танцы'
    фотография = 'фотография'


class MediaConsumption(Enum):
    минимальное = 'минимальное'
    умеренное = 'умеренное'
    высокое = 'высокое'
    очень_высокое = 'очень высокое'


class SocialActivity(Enum):
    одиночка = 'одиночка'
    малый_круг = 'малый круг'
    широкий_круг = 'широкий круг'
    тусовщик = 'тусовщик'


class WorkStatus(Enum):
    работает = 'работает'
    учится = 'учится'
    работает_и_учится = 'работает и учится'
    домохозяйка_домохозяин = 'домохозяйка/домохозяин'
    пенсионер = 'пенсионер'
    безработный = 'безработный'


class EducationLevel(Enum):
    неполное_среднее = 'неполное среднее'
    среднее = 'среднее'
    среднее_специальное = 'среднее специальное'
    неполное_высшее = 'неполное высшее'
    высшее = 'высшее'
    учёная_степень = 'учёная степень'


class LifestyleAndInterests(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    hobbies: list[Hobby] = Field(..., min_length=1)
    media_consumption: MediaConsumption = Field(
        ..., description='Общий уровень потребления медиа.'
    )
    social_activity: SocialActivity = Field(
        ..., description='Уровень социальной активности.'
    )
    work_status: WorkStatus = Field(..., description='Занятость.')
    education_level: EducationLevel = Field(..., description='Уровень образования.')


class PersonaDna(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    demographics: Demographics
    big_five: BigFive = Field(
        ...,
        description='Большая пятёрка (OCEAN). Decision Log #7: целые 1–5, не 0–1 и не проценты.',
    )
    values_and_beliefs: ValuesAndBeliefs
    viewer_behavior: ViewerBehavior = Field(
        ...,
        description='Зрительское поведение. Минимум 8 полей. Термин viewer_*, не consumer_*.',
    )
    communication_style: CommunicationStyle
    decision_making: DecisionMaking
    technology_usage: TechnologyUsage
    lifestyle_and_interests: LifestyleAndInterests
    narrative: constr(min_length=100) = Field(
        ...,
        description='Текстовое описание персоны в свободной форме: backstory, мотивация, характер.',
    )
    seed: conint(ge=0) = Field(..., description='Seed для воспроизводимости генерации.')
