# generated by datamodel-codegen:
#   filename:  respondent-session.schema.json
#   timestamp: 2026-08-02T04:58:10+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class ContentUnderTest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: constr(min_length=1)
    type: constr(min_length=1) = Field(
        ...,
        description='Открытая строка: в корпусе пока только «сериал», но полнометражные и рекламные ролики предполагаются.',
    )
    summary: str


class ExperimentMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    focus_group_city: constr(min_length=1)
    target_audience_segment: constr(min_length=1) = Field(
        ...,
        description='Сегмент, под который набиралась группа. Открытая строка: сегменты задаёт заказчик исследования.',
    )
    transcript_source_file: str


class Gender(Enum):
    жен = 'жен'
    муж = 'муж'


class AgeGroup(Enum):
    field_14_17 = '14-17'
    field_18_24 = '18-24'
    field_25_34 = '25-34'
    field_35_44 = '35-44'
    field_45_59 = '45-59'
    field_60_ = '60+'


class Geo(Enum):
    столицы = 'столицы'
    центры_субъектов = 'центры субъектов'


class SocioDemographics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gender: Gender
    age: conint(ge=14, le=120)
    age_group: AgeGroup = Field(
        ...,
        description='Словарь совпадает с persona-dna.schema.json. Расхождение делает метрику persona_grounding невычислимой.',
    )
    geo: Geo = Field(
        ..., description='Тип населённого пункта в терминах выборки исследования.'
    )
    city: constr(min_length=1)
    children: constr(min_length=1)


class PsychographicsAndValues(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    important_values: list[str] = Field(
        ...,
        description='Ценности, которые респондент считает важными. Открытый список: в корпусе 27 различных формулировок.',
    )


class InterestLevel(Enum):
    Скорее_интересен = 'Скорее интересен'
    Скорее_не_интересен = 'Скорее не интересен'
    Затрудняюсь_ответить = 'Затрудняюсь ответить'


class IdeaComprehension(Enum):
    Скорее_понятно = 'Скорее понятно'
    Скорее_не_понятно = 'Скорее не понятно'
    Затрудняюсь_ответить = 'Затрудняюсь ответить'


class RealismPerception(Enum):
    Скорее_реалистичные = 'Скорее реалистичные'
    Скорее_нереалистичные = 'Скорее нереалистичные'
    Затрудняюсь_ответить = 'Затрудняюсь ответить'


class RetentionIntent(Enum):
    Скорее_хотелось_досмотреть_до_конца = 'Скорее хотелось досмотреть до конца'
    Скорее_хотелось_остановить_просмотр = 'Скорее хотелось остановить просмотр'
    Затрудняюсь_ответить = 'Затрудняюсь ответить'


class QualitativeVerbatims(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    idea_comprehension_comment: str
    general_impression_comment: str
    why_impression: str | None = None


class Score(RootModel[conint(ge=1, le=10)]):
    root: conint(ge=1, le=10) = Field(..., description='Балл по шкале 1–10.')


class AgoraCoreScores1To10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    overall_impression: Score
    plot: Score
    acting: Score
    music: Score
    cinematography: Score


class PerceptionAndRetention(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interest_level: InterestLevel
    emotions_evoked: list[str] = Field(
        ...,
        description='Открытый список. ВНИМАНИЕ: в текущем корпусе сюда затесались подписи шкалы («10 – вызвал очень сильные эмоции») и голые числа — известный дефект данных, см. data/grounding/corpus.meta.json.',
    )
    idea_comprehension: IdeaComprehension
    realism_perception: RealismPerception
    retention_intent: RetentionIntent
    recommendation_nps_1_to_10: Score


class RespondentSession(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    respondent_id: constr(pattern=r'^.+_[0-9]+$') = Field(
        ...,
        description='Идентификатор вида «<Исследование>_<номер>». Производный от источника и порядкового номера, не от имени человека — обезличивание.',
    )
    source_file: constr(min_length=1) = Field(
        ...,
        description='Имя исходного файла анкет ЦЕЛИКОМ, с расширением. Ключ связи записи с исследованием.',
    )
    content_under_test: ContentUnderTest
    experiment_metadata: ExperimentMetadata
    socio_demographics: SocioDemographics
    psychographics_and_values: PsychographicsAndValues
    agora_core_scores_1_to_10: AgoraCoreScores1To10 = Field(
        ...,
        description='Пять базовых критериев AGORA. Именно по ним считается калибровка |средние−реальные| ≤ 1.0.',
    )
    perception_and_retention: PerceptionAndRetention
    qualitative_verbatims: QualitativeVerbatims = Field(
        ...,
        description='Открытые ответы из анкеты. why_impression заполнен не у всех: 156 записей из 165.',
    )
    focus_group_verbatims: list[str] = Field(
        ...,
        description='Срез групповой дискуссии под конкретного респондента: реплики с указанием говорящего. Получен моделью по промпту dataset.unification при первичной сборке корпуса и НЕ воспроизводится механически — см. corpus.meta.json.',
    )
    all_survey_responses: dict[str, str | float | bool | None] = Field(
        ...,
        description='Сырая анкета как есть: ключи — формулировки вопросов из XLSX, поэтому набор ключей различается между исследованиями. Намеренно ненормализованный слепок источника, нужен для прослеживаемости: по нему можно проверить любое нормализованное поле выше. Схема тут не ограничивает ключи — ограничение сделало бы добавление нового исследования невозможным.',
    )
